---
title: üßäExceptions
date: 2022-07-26 23:38:00
permalink: /pages/dc9bfe/
---

In the LiteFlow component, if an exception is thrown out, the chain will be interrupted. Except for setting the `ignoreError` keyword in [Parallel mode](/pages/b3446a/).

Outgoing exceptions are caught by the executor and wrapped in a `LiteflowResponse` object.

You can get exceptions in the `LiteflowResponse` object using the following methods

```java
LiteflowResponse response = flowExecutor.execute2Resp("chain1", initial parameters, CustomContext.class);
if (!response.isSuccess()){
  Exception e = response.getCause();
}
```

If your business needs to obtain the exception code, your custom exception needs to implement the `LiteFlowException` interface provided by LiteFlow:

```java
public class YourException extends LiteFlowException {
	public YourException(String code, String message) {
		super(code, message);
	}
}
```

If your business throws an exception that implements the `LiteFlowException` interface, you can get the message and code information in the `LiteflowResponse`:

```java
LiteflowResponse response = flowExecutor.execute2Resp("chain1", ÂàùÂßãÂèÇÊï∞, CustomContext.class);
if (!response.isSuccess()){
  Exception e = response.getCause();
  String code = response.getCode();
  String message = response.getMessage();
}
```

:::tip tip
If your exception does not implement `LiteFlowException`, the code and message fields are both null.
:::